# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

stages:

# ================================
# 1️⃣ BUILD STAGE
# ================================
- stage: Build
  displayName: "Build Stage"
  jobs:
  - job: BuildJob
    displayName: "Build and Publish"
    steps:

    - task: UseDotNet@2
      displayName: "Install .NET 8 SDK"
      inputs:
        packageType: 'sdk'
        version: '8.x'

    - task: DotNetCoreCLI@2
      displayName: "Restore"
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: "Build"
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: "Publish"
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true

    - task: PublishBuildArtifacts@1
      displayName: "Publish Artifact"
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'drop'


# ================================
# 2️⃣ DEPLOY STAGE
# ================================
- stage: Deploy
  displayName: "Deploy Stage"
  dependsOn: Build

  jobs:
  - deployment: DeployWeb
    displayName: "Deploy to Azure App Service"
    
    environment: "eShopOnWeb-dev"

    strategy:
      runOnce:
        deploy:
          steps:

          - task: DownloadBuildArtifacts@1
            displayName: "Download build artifacts"
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'

          - task: AzureWebApp@1
            displayName: "Deploy to WebApp"
            inputs:
              azureSubscription: "Azure subscription 1(9de0d732-3963-46b8-8e5c-ec8b8b6fe753)"
              appType: "webAppLinux"
              appName: "eShopOnWeb"
              package: "$(System.ArtifactsDirectory)/drop/*.zip"